### PR TITLE
Adding Menu Bar

### LINKED ISSUE #7: Task 4 -- Add a menu bar that dynamically displays other pages in the app

### PR DESCRIPTION
**Pull request by mlekhi**
Hey guys, I would appreciate some help with styling the menu bar!

### CODE REVIEW

**Comment by mlekhi** [comment]
image

**Comment by dilnazua** [comment]
image
Working on it currently

**Comment by josephmaa** [comment]
It's looking good

**Comment by mlekhi** [comment]
Love it! Once you commit those changes, we should be good to merge

**Pull request closed without merging**
